# Simple Mounts - Ver 1.0 (BETA)
# Author: Nicksarmour

# This plugin is designed to in the most simplest terms, provide simple mount store, summon, and simple customization

#Basic Configuration
basic:
  max-mounts: 3                         #Max is 8 mounts - More in the future
  is-breedable: true
  profanity-filtered: true

#To do with models / texture pack stuff
texture-pack:
  custom-whistle-sound: true            #Sound to be played is "custom.whistle"
  custom-model-data-whistle: 1

#Damage Configuration
damage:
  is-immortal: false
  #Must be not immortal for modifiers below to apply

  #Percentage of damage taken (As 0.xx form) with 1.00 being 100%
  damage-modifier: 0.25

  #Can the owner damage their own mount?
  owner-can-damage: true

  #when a mount dies, should it be removed from the inventory?
  can-respawn: false

#Attributes that are applied to a mount after they have been claimed -> 1.00 is normal. Recommended to disable breeding if changed
attributes:
  health-modifier: 1.00
  speed-modifier: 1.00
  jump-modifier: 1.00
